### ISSUE TITLE
Error in the ldap-passwd-reset service

### ISSUE THREAD

**Issue by harrydevine** [larrabee/freeipa-password-reset#22] opened 2019-09-30 17:21 UTC
I followed the installation instructions exactly, but when I start the ldap-passwd-reset service, I get the following in /var/log/messages:

Sep 30 13:19:10 auth1 systemd: Stopping FreeIPA Password Reset Service...
Sep 30 13:19:10 auth1 systemd: Stopped FreeIPA Password Reset Service.
Sep 30 13:19:10 auth1 systemd: Started FreeIPA Password Reset Service.
Sep 30 13:19:13 auth1 python: Unhandled exception in thread started by <function wrapper at 0x7f199a52d938>
Sep 30 13:19:13 auth1 python: detected unhandled Python exception in '/opt/data/IPAPasswordReset/PasswordReset/manage.py'
Sep 30 13:19:14 auth1 abrt-server: Executable '/opt/data/IPAPasswordReset/PasswordReset/manage.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Sep 30 13:19:14 auth1 abrt-server: 'post-create' on '/var/spool/abrt/Python-2019-09-30-13:19:14-1735' exited with 1
Sep 30 13:19:14 auth1 abrt-server: Deleting problem directory '/var/spool/abrt/Python-2019-09-30-13:19:14-1735'
Sep 30 13:19:14 auth1 python: Performing system checks...
Sep 30 13:19:14 auth1 python: Traceback (most recent call last):
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
Sep 30 13:19:14 auth1 python: fn(*args, **kwargs)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
Sep 30 13:19:14 auth1 python: self.check(display_num_errors=True)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
Sep 30 13:19:14 auth1 python: include_deployment_checks=include_deployment_checks,
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
Sep 30 13:19:14 auth1 python: return checks.run_checks(**kwargs)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
Sep 30 13:19:14 auth1 python: new_errors = check(app_configs=app_configs)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
Sep 30 13:19:14 auth1 python: return check_resolver(resolver)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
Sep 30 13:19:14 auth1 python: return check_method()
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
Sep 30 13:19:14 auth1 python: for pattern in self.url_patterns:
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
Sep 30 13:19:14 auth1 python: res = instance.__dict__[self.name] = self.func(instance)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
Sep 30 13:19:14 auth1 python: patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
Sep 30 13:19:14 auth1 python: res = instance.__dict__[self.name] = self.func(instance)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
Sep 30 13:19:14 auth1 python: return import_module(self.urlconf_name)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Sep 30 13:19:14 auth1 python: __import__(name)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/PasswordReset/PasswordReset/urls.py", line 20, in <module>
Sep 30 13:19:14 auth1 python: url(r'reset/', include('app.urls')),
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
Sep 30 13:19:14 auth1 python: urlconf_module = import_module(urlconf_module)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Sep 30 13:19:14 auth1 python: __import__(name)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/PasswordReset/app/urls.py", line 2, in <module>
Sep 30 13:19:14 auth1 python: from . import views
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/PasswordReset/app/views.py", line 10, in <module>
Sep 30 13:19:14 auth1 python: from pwdmanager import *
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/PasswordReset/app/pwdmanager.py", line 4, in <module>
Sep 30 13:19:14 auth1 python: from ipalib import api, errors as ipaerrors
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipalib/__init__.py", line 919, in <module>
Sep 30 13:19:14 auth1 python: from ipalib import plugable
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipalib/plugable.py", line 42, in <module>
Sep 30 13:19:14 auth1 python: from ipalib.config import Env
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipalib/config.py", line 43, in <module>
Sep 30 13:19:14 auth1 python: from ipaplatform.tasks import tasks
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipaplatform/tasks.py", line 10, in <module>
Sep 30 13:19:14 auth1 python: ipaplatform._importhook.fixup_module('ipaplatform.tasks')
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipaplatform/_importhook.py", line 135, in load_module
Sep 30 13:19:14 auth1 python: platform_mod = importlib.import_module(alias)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Sep 30 13:19:14 auth1 python: __import__(name)
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipaplatform/rhel/tasks.py", line 26, in <module>
Sep 30 13:19:14 auth1 python: from ipaplatform.redhat.tasks import RedHatTaskNamespace
Sep 30 13:19:14 auth1 python: File "/usr/lib/python2.7/site-packages/ipaplatform/redhat/tasks.py", line 56, in <module>
Sep 30 13:19:14 auth1 python: """)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 105, in cdef
Sep 30 13:19:14 auth1 python: self._cdef(csource, override=override, packed=packed)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 119, in _cdef
Sep 30 13:19:14 auth1 python: self._parser.parse(csource, override=override, **options)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 299, in parse
Sep 30 13:19:14 auth1 python: self._internal_parse(csource)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 304, in _internal_parse
Sep 30 13:19:14 auth1 python: ast, macros, csource = self._parse(csource)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 260, in _parse
Sep 30 13:19:14 auth1 python: ast = _get_parser().parse(csource)
Sep 30 13:19:14 auth1 python: File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 40, in _get_parser
Sep 30 13:19:14 auth1 python: _parser_cache = pycparser.CParser()
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/pycparser/c_parser.py", line 116, in __init__
Sep 30 13:19:14 auth1 python: outputdir=taboutputdir)
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 3256, in yacc
Sep 30 13:19:14 auth1 python: signature = pinfo.signature()
Sep 30 13:19:14 auth1 python: File "/opt/data/IPAPasswordReset/virtualenv/lib/python2.7/site-packages/pycparser/ply/yacc.py", line 2961, in signature
Sep 30 13:19:14 auth1 python: digest = base64.b16encode(sig.digest())
Sep 30 13:19:14 auth1 python: UnboundLocalError: local variable 'sig' referenced before assignment

This is a RHEL 7.7 with IDM 4.6.5 and FIPS enabled.

**Comment by larrabee** [comment] 2019-09-30 20:41
Duplicate of #16.

**Closed by larrabee** 2019-09-30 20:41 UTC
